Client 593
cherrytwist/client-web pull request #619
Opened 2021-06-11 14:27 UTC by hero101

### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/cherrytwist/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/cherrytwist/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/cherrytwist/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

2021-06-12 07:41 UTC, techsmyth approved these changes
Was working nicely for me. So great to finally have this coming together...

Will leave detail code review to Angel.

2021-06-14 10:27 UTC, atstojanov requested changes

2021-06-14 10:27 UTC, atstojanov commented on src/hooks/useUserMetadataWrapper.ts
> +        ofEcoverse: (id: string) => hasCredentials(AuthorizationCredential.UserGroupMember, id),
The AuthorizationCredential should be `ChallengeMemeber` and  `EcoverseMember`.

2021-06-15 06:36 UTC, atstojanov approved these changes

2021-06-15 06:36 UTC, merged