Reference management simplification
cherrytwist/client-web pull request #685
Opened 2021-06-28 16:04 UTC by atstojanov

### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/cherrytwist/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/cherrytwist/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/cherrytwist/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

2021-06-28 18:27 UTC, techsmyth reviewed
Working very nicely on ecoverse. And code looks much cleaner.

However when I tried it on my user profile + adding multiple references I got errors...

Also saw the following error on the server:

![image](https://user-images.githubusercontent.com/30729240/123685924-80367280-d84f-11eb-90bc-8d541e46aad3.png)

2021-06-29 08:00 UTC, hero101 requested changes

2021-06-29 08:00 UTC, hero101 commented on src/components/Admin/Common/ContextReferenceSegment.tsx
> +  return <ReferenceSegment {...rest} onAdd={handleAdd} onRemove={handleRemove} readOnly={!contextId || readOnly} />;
Maybe a spread is not a good idea.

2021-06-29 08:00 UTC, hero101 commented on src/components/Admin/Common/ProfileReferenceSegment.tsx
> +  return <ReferenceSegment {...rest} onAdd={handleAdd} onRemove={handleRemove} readOnly={!profileId || readOnly} />;
Maybe a spread is not a good idea.

2021-06-29 08:00 UTC, hero101 commented on src/components/Admin/Common/ReferenceSegment.tsx
> +export interface ReferenceSegmentProps {
Do you need that exported?

2021-06-29 12:26 UTC, techsmyth approved these changes
Working smoothly and fast for me :)

2021-06-29 12:27 UTC, merged